# Generated by Django 4.2.2 on 2023-06-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.CharField(default=True, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
