# Generated by Django 4.2.2 on 2023-06-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_todo_user_todo_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
