# Generated by Django 4.2.2 on 2023-06-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0010_alter_todo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.IntegerField(editable=False, max_length=232, primary_key=True, serialize=False),
        ),
    ]
